version: '3'
services:

# Development service
  app-dev:
    container_name: boxful-api-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - DB_URI=${DB_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo
    

  mongo:
    image: mongo
    container_name: boxful-mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db

# Production service
  app-prod:
    container_name: boxful-api-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    command: npm run start:prod
    ports:
      - "3000:3000"
    environment:
      - DB_URI=${DB_URI}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo
      
